/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test;

import static org.junit.Assert.*;

import org.junit.Test;

import haday.demo.Library;

public class LibraryTest {
	@Test
	public void testSomeLibraryMethod() {
		Library classUnderTest = new Library();
		assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
	}
}
