server:
   port: 8083

spring:
   redis:
      host: 127.0.0.1
      port: 6379
      password: 
      database: 5
      timeout: 1000ms
      jedis:
         pool:
            max-active: 200
            max-wait: 1ms
            max-idle: 10
            min-idle: 0


logging: 
   config: classpath:log4j2.xml


   
   